# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CivicSimUI
                                 A QGIS plugin
 a path finding algorithm for real world problems
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-12-26
        copyright            : (C) 2023 by anythingmapping.com
        email                : anythingmapping@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CivicSimUI class from file CivicSimUI.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .CivicSim import CivicSimUI
    return CivicSimUI(iface)
